version: "2.4"
volumes:
  #xserver-volume:
  settings: # Only required if using PERSISTENT flag (see below)
  shared-certs: # New volume for sharing certificates

services:

  certs:
    build:
      context: ./certs
      dockerfile: Dockerfile.init-certs
    volumes:
      - shared-certs:/shared-certs
    command: ["sh", "-c", "cp -r /certs/* /shared-certs/ && echo 'Certificates copied' && sleep 3600"]

  display:
    build: ./balena-display
    privileged: true
    network_mode: host
    environment:
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
      - LAUNCH_URL_1=https://google.com
      - LAUNCH_URL_2=https://bing.com
      - SHOW_CURSOR=1
    labels:
      io.balena.features.dbus: '1'


  # browser:
  #   build: ./browser-2.7.0
  #   restart: always
  #   privileged: true # required for UDEV to find plugged in peripherals such as a USB mouse
  #   volumes:
  #     - "settings:/data" # Only required if using PERSISTENT flag (see below)
  #     - "shared-certs:/certs" # Mount the shared volume
  #   environment:
  #     - DISPLAY_NUM=0 # hat gerade keinen Einfluss, da 2x überschieben
  #     - SHOW_CURSOR=1
  #     - ENABLE_GPU=1
  #     - KIOSK=0
  #     - LAUNCH_URL_1=https://app:8082?display=1
  #     - WINDOW_SIZE_1=1280,800 #Touchscreen Fannal 10.1" #4k: 43840, 2160
  #     - WINDOW_POSITION_1=0,0 #second screen 0 = 2xResX  because of bug!!! (bsp. 2560)
  #     - LAUNCH_URL_2=https://app:8082?display=2
  #     - WINDOW_SIZE_2=1280,800 #Touchscreen Fannal 10.1" #4k: 43840, 2160
  #     - WINDOW_POSITION_2=2560,0 #second screen 0 = 2xResX  because of bug!!! (bsp. 2560)
  #     # - EXTRA_FLAGS= --disable-pinch
  #   depends_on:
  #     - app
  #     - certs

  app:
    hostname: app
    build: ./app
    restart: always
    privileged: true
    volumes:
      - "shared-certs:/certs" # Mount the shared volume
    ports:
      - "3000:3000"
      #- "8081:8081" # Internal HTTP port
      - "8082:8082" # External HTTPS port for SSL proxy
    environment:
      - PORT=3000
    depends_on:
      - certs

  devices:
    hostname: devices
    build: ./devices
    restart: always
    privileged: true
    volumes:
      - "shared-certs:/certs" # Mount the shared volume
    depends_on:
      - certs

  # toto:
  #   hostname: toto
  #   build: ./toto
  #   restart: always
  #   privileged: true
  #   volumes:
  #     - "shared-certs:/certs" # Mount the shared volume