version: '2.4'
volumes:
    xserver-volume:
networks:
  custom_network:  # Add this line
    driver: bridge
services:
  xserver:
    image: balenablocks/xserver
    restart: always
    privileged: true
    command: ["-ac"]
    volumes:
      - 'xserver-volume:/tmp/.X11-unix'
    networks:  # Add these lines
      - custom_network
  orchester:
    build: ./orchester
    restart: always
    privileged: true
    hostname: orchester
    networks:  # Add these lines
      - custom_network
  kiosk:
    build: ./kiosk
    restart: always
    privileged: true
    hostname: kiosk
    volumes:
      - 'xserver-volume:/tmp/.X11-unix'
    environment:
      - DISPLAY=:0
      #- ELECTRON_ENABLE_HW_ACCELERATION=1
    networks:  # Add these lines
      - custom_network
