version: "2.4"
volumes:
  xserver-volume:
  settings: # Only required if using PERSISTENT flag (see below)

services:
  browser:
    image: bh.cr/balenalabs/browser-amd64/2.5.1 # where <arch> is one of aarch64, arm32 or amd64 (getestet bis. 2.5.1 läuft, 2.5.2 läuft nicht) 
    build: ./browser-2.7.0
    restart: always
    privileged: true # required for UDEV to find plugged in peripherals such as a USB mouse
    volumes:
      - "settings:/data" # Only required if using PERSISTENT flag (see below)
    environment:
      - LAUNCH_URL=http://app:8080?display=1
      - SHOW_CURSOR=1
      - ENABLE_GPU=1
      - KIOSK=1
      # - FLAGS= --enable-accelerated-video-decode --disable-context-menu --disable-pinch --lang=de
      # - LOCAL_HTTP_DELAY=10
      # - FLAGS=--disable-pinch
      - WINDOW_SIZE=1280,800 # Touchscreen Fannal 10.1"
      # - WINDOW_SIZE=43840, 2160
    ports:
      - "5011" # management API (optional)

  # display:
  #   build: ./display-pi5
  #   privileged: true
  #   environment:
  #     - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
  #     - LAUNCH_URL_1=http://app:8080?display=1
  #     - LAUNCH_URL_2=http://app:8080?display=2
  #   labels:
  #     io.balena.features.dbus: '1'

  app:
    build: ./app
    restart: always
    privileged: true
    hostname: app
    ports:
    #  - "3000:3000"
      - "8080:8080"
    environment:
      - PORT=8080
    # depends_on:
    #  - browser
    #  - devices

  devices:
    build: ./devices
    restart: always
    privileged: true
    hostname: devices

  # toto:
  #   build: ./toto
  #   restart: always
  #   privileged: true
  #   hostname: toto
  #   environment:
  #     - WEBSOCKET_SERVER_URI=ws://orchester:8765
