version: "2.4"
volumes:
  #xserver-volume:
  settings: # Only required if using PERSISTENT flag (see below)
  shared-certs: # New volume for sharing certificates

services:

  certs-init:
    build:
      context: ./certs
      dockerfile: Dockerfile.init-certs
    volumes:
      - shared-certs:/shared-certs
    command: ["sh", "-c", "cp -r /certs/* /shared-certs/ && echo 'Certificates copied' && sleep 3600"]

  browser1:
    build: ./browser-2.7.0
    restart: always
    privileged: true # required for UDEV to find plugged in peripherals such as a USB mouse
    volumes:
      - "settings:/data" # Only required if using PERSISTENT flag (see below)
      - "shared-certs:/certs" # Mount the shared volume
    environment:
      #- LAUNCH_URL=https://app:8082?display=1
      - DISPLAY_NUM=0
      - SHOW_CURSOR=1
      - ENABLE_GPU=1
      - KIOSK=0
      # - EXTRA_FLAGS= --disable-pinch
      - WINDOW_SIZE=1280,800 #Touchscreen Fannal 10.1" #4k: 43840, 2160

  app:
    hostname: app
    build: ./app
    restart: always
    privileged: true
    volumes:
      - "shared-certs:/certs" # Mount the shared volume
    ports:
      - "8081:8081" # Internal HTTP port
      - "8082:8082" # External HTTPS port for SSL proxy
    environment:
      - PORT=8081

  # devices:
  #   hostname: devices
  #   build: ./devices
  #   restart: always
  #   privileged: true
  #   volumes:
  #     - "shared-certs:/certs" # Mount the shared volume

  # toto:
  #   hostname: toto
  #   build: ./toto
  #   restart: always
  #   privileged: true
  #   volumes:
  #     - "shared-certs:/certs" # Mount the shared volume