version: '2.4'
volumes:
    xserver-volume:

networks:
  custom_network:  
    driver: bridge

services:
  xserver:
    image: balenablocks/xserver
    restart: always
    privileged: true
    command: ["-ac"]
    volumes:
      - 'xserver-volume:/tmp/.X11-unix'

  kiosk:
    build: ./kiosk
    restart: always
    privileged: true
    hostname: kiosk
    volumes:
      - 'xserver-volume:/tmp/.X11-unix'
    environment:
      - DISPLAY=:0
    networks:  
      - custom_network

  orchester:
    build: ./orchester
    restart: always
    privileged: true
    hostname: orchester
    networks:  
      - custom_network

  toto:
    build: ./toto
    restart: always
    privileged: true
    hostname: toto
    networks:  
      - custom_network
