version: '2.4'
volumes:
  xserver-volume:
  settings:                          # Only required if using PERSISTENT flag (see below)

services:
  browser:
    build: ./browser
    restart: always
    privileged: true # required for UDEV to find plugged in peripherals such as a USB mouse
    volumes:
      - 'settings:/data' # Only required if using PERSISTENT flag (see below)
    environment:
      - LAUNCH_URL=http://app:8081?display=2
      - SHOW_CURSOR=1
      - ENABLE_GPU=1
      - KIOSK=0
      - FLAGS= --enable-accelerated-video-decode --disable-context-menu --disable-pinch --lang=de
     # - LOCAL_HTTP_DELAY=10
     # - FLAGS=--disable-pinch
     # - WINDOW_SIZE=1980,1080
      - WINDOW_SIZE=43840, 2160
    ports:
      - '5011' # management API (optional)

  browsercontrol:
    image: balenablocks/browsercontrol
    restart: always
    network_mode: host
    privileged: true
    ports:
      - 80:80
  
  app:
    build: ./app
    restart: always
    privileged: true
    hostname: app
    ports:
      - "8081:8081"
    environment:
      - PORT=8081

  orchester:
    build: ./orchester
    restart: always
    privileged: true
    hostname: orchester

  devices:
    build: ./devices
    restart: always
    privileged: true
    hostname: devices
    environment:
      - WEBSOCKET_SERVER_URI=ws://orchester:8765

  toto:
    build: ./toto
    restart: always
    privileged: true
    hostname: toto
    environment:
      - WEBSOCKET_SERVER_URI=ws://orchester:8765
